fix error so it goes to stdout, not the return string of the function

diff --git a/ceph/bc-ceph-create-osd b/ceph/bc-ceph-create-osd
--- a/ceph/bc-ceph-create-osd
+++ b/ceph/bc-ceph-create-osd
@@ -192,8 +192,8 @@ create_journal() {
 
     d=$(diff -u0 <(echo "$old") <(echo "$new") | tail -n1)
     if ! grep -qE "\+[ ]+[0-9]+[ ]+[0-9]+[ ]+[0-9]+[ ]+$(grep -Eo '[0-9]+'<<< "$journal_size")" <<< "$d"; then
-        echo "ERROR: the sgdisk name workaround failed... giving up. The diff between old and new partition table:"
-        echo "$d"
+        echo "ERROR: the sgdisk name workaround failed... giving up. The diff between old and new partition table:" >&2
+        echo "$d" >&2
         return 1
     fi
     start=$(awk '{print $3}' <<< "$d")
